language: java
jdk:
  - oraclejdk8
  - oraclejdk7
before_install:
  # ensure gradlew has proper permission
  # - chmod a+x ./gradlew
script:
  # test using maven
  - mvn clean compile
  # uncomment below to test using gradle
  # - gradle test
  # uncomment below to test using sbt 
  # - sbt test
